databases:
  - name: chemdb
    plan: free
    databaseName: chemdb
    user: chemdb

services:
  - type: web
    plan: free
    name: chem_inventory
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn chem_inventory.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chemdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4