# Generated by Django 4.2.21 on 2025-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.TextField()),
                ('room', models.TextField()),
                ('location', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
